# --- General options --- #

# Name of website
title: Xusheng Ji

# Short description of your site
description: Data-intensive application

markdown: kramdown
#remote_theme: pmarsceill/just-the-docs

theme: jekyll-theme-hacker
